### ISSUE TITLE
Window size with Favorites

### ISSUE THREAD

**Issue by Perelandra0x309** [humdingerb/quicklaunch#16] opened 2017-10-12 14:27 UTC
When you have favourites, sometimes when launching QL the window is resized so that you need to scroll to see the last item.  Happens about 1/6 times.  I cannot find a pattern, whether using the arrows to select the item, or whatever.  Just try launching QL, pressing ENTER to launch the first favourite, launch QL again and do this many times and see what happens.  Usually randomly the window will be slightly smaller so the last item needs to be scrolled to.

**Comment by humdingerb** [comment] 2017-10-12 14:36
I tried that a few dozen times now, but it didn't happen yet... How many favorites do you have?

**Comment by Perelandra0x309** [comment] 2017-10-12 15:03
I saw it happen with 2 and 4.  I am on hrev51429

**Comment by Perelandra0x309** [comment] 2017-10-12 15:14
![screenshot12](https://user-images.githubusercontent.com/22124003/31503709-5f1e4e76-af3e-11e7-8f2e-8389c8bee59c.png)
![screenshot13](https://user-images.githubusercontent.com/22124003/31503713-61269e94-af3e-11e7-80da-1668b188b2cc.png)

I've used the Shortcuts preflet to map Option (Either) - Q to QuickLaunch.  Even just doing Option-Q, ESC, Option-Q, ESC, etc produces it.

**Comment by humdingerb** [comment] 2017-10-12 16:14
I'll look out for it, but up to now was unable to reproduce...
I even set the system font size back to 12 and show the app versions. :)

**Comment by humdingerb** [comment] 2018-11-02 16:47
Should be fixed with 471d060d4ac81b9e6613a79bc2b3b8104b1873dd.
It must've been some kind of race condition where the resizing was done when the layout of the window wasn't finished yet. By sending a BMessage to filter the list (which does a ResizeWindow() at the end this is avoided, because the BMessage will be processed only after the MainWindow is ready.
At least that's my theory... :)

**Closed by humdingerb** 2018-11-02 16:47 UTC
